kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: prepare
    image: node:20.13.0
    commands:
      - npm run ci:prepare-docker

  - name: server-build-image
    image: docker:dind
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build --progress plain --compress -t paperplanecc/paperplane-web-console:${DRONE_COMMIT_SHA:0:8} .

  - name: server-stop-old-container
    image: docker:dind
    failure: ignore
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker stop paperplane-web-console
      - docker rm paperplane-web-console

  - name: server-rename-old-image
    image: docker:dind
    failure: ignore
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker tag paperplanecc/paperplane-web-console:production paperplanecc/paperplane-web-console:previous-prod
      - docker rmi paperplanecc/paperplane-web-console:production

  - name: server-prisma-sync-db
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - cd /root/project-config/paperplane-web-console
        - |
          docker run -t --rm --name paperplane-web-console-prisma --network root_default -e NODE_ENV=production \
          -v ./.env.production.local:/paperplane-web-console/packages/db/.env.production.local:ro \
          paperplanecc/paperplane-web-console:${DRONE_COMMIT_SHA:0:8} pnpm db:deploy

  - name: server-deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - docker tag paperplanecc/paperplane-web-console:${DRONE_COMMIT_SHA:0:8} paperplanecc/paperplane-web-console:production
        - cd /root/project-config/paperplane-web-console
        - docker compose up -d

  - name: website-extract-dist
    image: docker:dind
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker cp paperplane-web-console:/paperplane-web-console/package/web/dist ./

  - name: website-deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint: https://cos.ap-hongkong.myqcloud.com
      region: ap-hongkong
      bucket: paperplane-cdn-1253277322
      access_key:
        from_secret: COS_SECRET_ID
      secret_key:
        from_secret: COS_SECRET_KEY
      source: /paperplane-web-console/dist/**/*
      target: /paperplane-web-console
      strip_prefix: /paperplane-web-console/dist

  - name: website-backup-old
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-web-console-bak/
      - rm -rf /webroot/paperplane-web-console-bak/*
      - cp -rf /webroot/paperplane-web-console/ /webroot/paperplane-web-console-bak/

  - name: website-deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-web-console/
      - cp -rf /paperplane-web-console/dist/* /webroot/paperplane-web-console/

  - name: clean-image
    image: docker:dind
    failure: ignore
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker rmi paperplanecc/paperplane-web-console:previous-prod
      - docker rmi paperplanecc/paperplane-web-console:${DRONE_COMMIT_SHA:0:8}

  - name: clean-website-backup
    image: ubuntu:22.04
    failure: ignore
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - rm -rf /webroot/paperplane-web-console-bak

  - name: rollback-handle-docker
    image: docker:dind
    when:
      status:
        - failure
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker stop paperplane-web-console || true
      - docker rm   paperplane-web-console || true
      - docker rmi  paperplanecc/paperplane-web-console:production || true
      - docker rmi  paperplanecc/paperplane-web-console:${DRONE_COMMIT_SHA:0:8} || true

  - name: rollback-handle-ssh
    image: appleboy/drone-ssh
    when:
      status:
        - failure
    settings:
      host:
        - 'paperplane.cc'
      username: root
      key:
        from_secret: DEPLOY_SSH_PRIKEY
      command_timeout: 5m
      script:
        - docker tag paperplanecc/paperplane-web-console:previous-prod paperplanecc/paperplane-web-console:production || true
        - docker rmi paperplanecc/paperplane-web-console:previous-prod || true
        - cd /root/project-config/paperplane-web-console
        - docker compose up -d

  - name: rollback-handle-website
    image: ubuntu:22.04
    when:
      status:
        - failure
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - cp -rf /webroot/paperplane-web-console-bak/* /webroot/paperplane-web-console/
      - rm -rf /webroot/paperplane-web-console-bak/*

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: webroot
    host:
      path: /root/www

trigger:
  branch:
    - main
