packages:
  - 'packages/*'

catalog:
  "@eslint/js": ^9.17.0
  "@trivago/prettier-plugin-sort-imports": ^4.3.0
  eslint: ^9.17.0
  eslint-config-prettier: ^9.1.0
  eslint-config-react-app: ^7.0.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.16
  globals: ^15.14.0
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  typescript: ^5.7.2
  typescript-eslint: ^8.18.2

